server:
  port: 8082
eureka:
    instance:
        perferIpAddress: true
        hostname: server2
    #在默认情况下erureka server也是一个eureka client ,必须要指定一个 server
    client:
        #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
        registerWithEureka: true
        #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
        fetchRegistry: true
        serviceUrl:
            #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@server1:8081/eureka/

#注册中心安全配置,需要在Eureka-server添加依赖，服务端也需要添加
spring:
  profiles: server2
  application:
    name: server2

  security:
    user:
      name: liqian  # 用户名
      password: 123456 # 用户密码


